---
title: ANN
output:
  html_document: 
    toc: yes
  pdf_document: default
---

# Loading Data

```{r}
X <- read.csv("./data/X_.csv", header = TRUE)
y <- read.csv("./data/y_.csv", header = TRUE)
```

# Dataset Division

```{r}
data <- cbind(X, y)
indices <- 1:nrow(data)
set.seed(123) 
shuffled_indices <- sample(indices) 
train_size <- floor(0.7 * length(indices))

train_indices <- shuffled_indices[1:train_size]
test_indices <- shuffled_indices[(train_size + 1):length(indices)]
train_data <- data[train_indices, ]
test_data <- data[test_indices, ]
```

# ANN Training

```{r}
library(neuralnet)

# 设计ANN模型结构
ann_formula <- as.formula("dod ~ .")
ann_model <- neuralnet(ann_formula, data = train_data, hidden = c(20, 10), linear.output = FALSE, act.fct = "logistic")

# 模型训练
trained_model <- ann_model
```

# Prediction

```{r}
predictions <- compute(trained_model, test_data[, -ncol(test_data)])$net.result
```

# Performance
```{r}
threshold <- 0.5
predicted_classes <- ifelse(predictions > threshold, 1, 0)

# 计算准确率
accuracy <- sum(predicted_classes == test_data[, ncol(test_data)]) / nrow(test_data)
cat("Accuracy:", accuracy, "\n")

# 计算召回率
recall <- sum(predicted_classes == 1 & test_data[, ncol(test_data)] == 1) / sum(test_data[, ncol(test_data)] == 1)
cat("Recall:", recall, "\n")

# 计算F1分数
precision <- sum(predicted_classes == 1 & test_data[, ncol(test_data)] == 1) / sum(predicted_classes == 1)
f1_score <- 2 * (precision * recall) / (precision + recall)
cat("F1 Score:", f1_score, "\n")
```

# ROC Curve
```{r}
library(pROC)
roc_obj <- roc(test_data[, ncol(test_data)], predictions)

plot(
  roc_obj,
  col = "red", 
  main = "ROC Curve - ANN",
  legacy.axes = T,
  print.auc = TRUE,
  print.thres = TRUE,
  grid=c(0.2,0.2),
  grid.col=c("blue","yellow")
)
```
