---
title: "logistic_regression_dod"
author: "XU KE"
date: "2023-11-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Logistic Regression

## 加载数据

```{r}
X <- read.csv("X.csv", header = TRUE)
y <- read.csv("y.csv", header = TRUE)
```

## 划分训练集和测试集

```{r}
 
data <- cbind(X, y)

set.seed(123) # 可以修改的随机种子
indices <- 1:nrow(data)
shuffled_indices <- sample(indices)
train_size <- floor(0.8 * length(indices)) # 修改比例
train_indices <- shuffled_indices[1:train_size]
test_indices <- shuffled_indices[(train_size + 1):length(indices)]

train_data <- data[train_indices, ]
test_data <- data[test_indices, ]
```

## 逻辑回归 - 使用AIC

```{r}
library('MASS')
library('caret')
logit_model <- glm(dod ~ ., data = train_data, family = binomial)
step_model <- stepAIC(logit_model, direction = "both")
```

```{r}
summary.glm(step_model)
```

```{r}
# ci <- confint(step_model)
# print(ci)
# exp(coef(step_model))
# exp(cbind(OR <- coef(step_model), ci))

predictions <- predict(step_model, test_data)
```

# Evaluation

## ROC Curve

```{r}
library(pROC)
roc_obj <- roc(test_data[, ncol(test_data)], predictions)

plot(roc_obj,col="red",#颜色
     main="ROC Curve - Logistic Regression",
     legacy.axes=T,#y轴格式更改
     print.auc=TRUE,#显示AUC面积
     print.thres=TRUE,#添加截点和95%CI
     grid=c(0.2,0.2),grid.col=c("blue","yellow"))#网格线设置
```
